/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xae18_fotopriv_NativeClass */

#ifndef _Included_com_xae18_fotopriv_NativeClass
#define _Included_com_xae18_fotopriv_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xae18_fotopriv_NativeClass
 * Method:    getStringFromNative
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xae18_fotopriv_NativeClass_getStringFromNative
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_xae18_fotopriv_NativeClass
 * Method:    registerUser
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xae18_fotopriv_NativeClass_registerUser
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
